### ISSUE TITLE
Space calculation fails for symlinks

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Vacuum#33]
I have a symlink in my temp folder called `Application Data`. Whenever I execute `vacuum -s 500M`, it fails:

```
vacuum -s 500M
Cleaning directory T:\Temp\
Cleaning 524288000 bytes
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'T:\Temp\Application Data\Application Data' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 77
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Vacuum.Program.getEntrySize(String path) in D:\X-Files\Projects\Vacuum\Vacuum\Program.fs:line 72
   at Vacuum.Program.takeBytes@78.GenerateNext(IEnumerable`1& next) in D:\X-Files\Projects\Vacuum\Vacuum\Program.fs:line 83
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 77
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 494
   at Microsoft.FSharp.Collections.SeqModule.groupByRefType[T,TKey](FSharpFunc`2 keyf, IEnumerable`1 seq) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 1070
   at Microsoft.FSharp.Collections.SeqModule.GroupBy@1076-1.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 1076
   at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@469.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 469
   at Microsoft.FSharp.Collections.SeqModule.revamp@574.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 574
   at Microsoft.FSharp.Collections.MapTreeModule.ofSeq[TKey,T](IComparer`1 comparer, IEnumerable`1 c) in E:\A\_work\130\s\src\fsharp\FSharp.Core\map.fs:line 373
   at Microsoft.FSharp.Collections.FSharpMap`2.Create(IEnumerable`1 ie) in E:\A\_work\130\s\src\fsharp\FSharp.Core\map.fs:line 491
   at Microsoft.FSharp.Collections.MapModule.OfSeq[TKey,T](IEnumerable`1 elements) in E:\A\_work\130\s\src\fsharp\FSharp.Core\map.fs:line 808
   at Vacuum.Program.clean(String directory, DateTime date, FSharpOption`1 bytesToFree) in D:\X-Files\Projects\Vacuum\Vacuum\Program.fs:line 110
   at Vacuum.Program.main(String[] args) in D:\X-Files\Projects\Vacuum\Vacuum\Program.fs:line 134
```

**Comment by ForNeVeR** [comment]
It shouldn't follow the symlinks at all, I think.

**Comment by ForNeVeR** [comment]
Duplicate of #45.
