### ISSUE TITLE
Error while checking directory that was deleted by external process

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Vacuum#6]
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\50341ea4-986a-432a-829e-9631093b5b32.tempbin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFileSystemEntries(String path, String searchPattern, SearchOption searchOption)
   at Vacuum.Program.needToRemoveTopLevel(DateTime date, String path) in E:\Projects\Vacuum\Vacuum\Program.fs:line 37
   at Vacuum.Program.states@69-3.Invoke(String path) in E:\Projects\Vacuum\Vacuum\Program.fs:line 69
   at Microsoft.FSharp.Collections.IEnumerator.next@224[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)
   at Microsoft.FSharp.Collections.IEnumerator.filter@219.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Microsoft.FSharp.Collections.SeqModule.groupByRefType[T,TKey](FSharpFunc`2 keyf, IEnumerable`1 seq)
   at Microsoft.FSharp.Collections.SeqModule.GroupBy@1491-1.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@881.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.revamp@987.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.MapTreeModule.ofSeq[TKey,T](IComparer`1 comparer, IEnumerable`1 c)
   at Microsoft.FSharp.Collections.FSharpMap`2.Create(IEnumerable`1 ie)
   at Microsoft.FSharp.Collections.MapModule.OfSeq[TKey,T](IEnumerable`1 elements)
   at Vacuum.Program.clean(String directory) in E:\Projects\Vacuum\Vacuum\Program.fs:line 67
   at Vacuum.Program.main(String[] _arg1) in E:\Projects\Vacuum\Vacuum\Program.fs:line 88
```

**Comment by ForNeVeR** [comment]
Already fixed before v1.6.0.
